### PR TITLE
feat(presenter): optimize and fixes

### LINKED ISSUE #50: 🐛 [Bug] Home Page – Collection Issue for Bug Fixes
## 🐛 Bug

Collection issue for bug fixes for the home page.

#### Browsers

- [ ] Safari:
  - [x] macOS
  - [ ] iOS
- [ ] FireFox:
  - [ ] macOS
- [ ] Edge:
  - [ ] Windows
- [ ] Chrome:
  - [ ] Android

#### Design

- [ ] controls (ugly clipped) in the animation video in Safari on start and hover:

Bildschirmfoto 2023-12-13 um 13 07 38

Bildschirmfoto 2023-12-13 um 13 09 11

- [ ] slider controls are visible (on hover):
  - shall that be a slider at all?
    - please talk to me ( @Tirokk )

Bildschirmfoto 2023-12-15 um 11 59 14

- [ ] `DreamMall Planning`:
  - do we want a reload button?

Bildschirmfoto 2023-12-15 um 13 25 33

- [ ] `Newsletter`:
  - [x] e-mail field: is to short
  - [ ] send e-mail does not work yet
  - [x] `Datenschutzrichtilinie` link does not work
  - [x] `Aktuellen Newsletter`  →  `Aktueller Newsletter:`
  - [x] `DOWNLOAD` button does not work

Bildschirmfoto 2023-12-15 um 13 35 55

- [x] `Deine Zutaten im Kaffee`:
  - [x] `Weltencafé` slide:
    - [x] overlap of the slider left arrow control with the text of the most left icon
  - [x] `Mall` slide:
    - [x] the `Mall` header icon should be designed in proportions like the `Weltencafé` icon
    - [x] icons looking to big in proportion to the headline texts and in relation to the first slide
  - [x] `Menschen Und Projekte` slide:
    - [x] the `Menschen Und Projekte` header icon should be designed in proportions like the `Weltencafé` icon
    - [x] icons looking to big in proportion to the headline texts and in relation to the first slide

Bildschirmfoto 2023-12-15 um 15 21 18

Bildschirmfoto 2023-12-15 um 15 34 30

Bildschirmfoto 2023-12-15 um 15 41 35

##### Imprint

- [x] headline `Impressum` is clipped:

Bildschirmfoto 2023-12-15 um 16 05 03

#### Text

- [x] header:
  - [x] `Kontakt`  →  `kontakt`
- [ ] `Respektvolles Miteinander Macht ALLES Möglich.`
  - [ ] usually in German headlines are not written with capital letters at the beginning of all main words:
    - [ ] maybe this is done by the VuePress framework? because on copy and past it is correct
      - [ ] seems to be a language-dependent behavior
        - [ ] possible explanation:
          - [ ] my check in the code says that there's German language in the `en` locale and probably `en` is default
          - [ ] and we have no language switch to check the differences
    - [ ] exceptions may be design reasons
  - [ ] shall this headline end with a dot?
- [ ] `Euch` in small caps:
  - [ ] `Die DreamMall Plattform bietet Euch Unternehmern,`  →  `Die DreamMall Plattform bietet euch Unternehmern,`
    - see https://www.scribbr.de/gross-und-kleinschreibung/euch/#:~:text=Du%20kannst%20das%20Anredepronomen%20‚euch,klar%20ist%2C%20wer%20angesprochen%20wird.
- [ ] `Eure` in small caps:
  - [ ] `vertrauensvollen Raum der kreativen Vernetzung für Eure Ideen und`  →  `vertrauensvollen Raum der kreativen Vernetzung für eure Ideen und`
    - same same
- [x] `Menschen Und Pr…`  →  `Menschen und Pr…`?
  - [x] and no ellipse `…`?
- [x] `Verwirklichen deine Kreativität in die Realität.`  →  `Verwirkliche deine Kreativität in der Realität.`

Bildschirmfoto 2023-12-15 um 12 59 51

- [ ] `Deine Zutaten im Kaffee`:
  - [ ] `Weltencafé` slide:
    - [ ] `Alle Funktionen die du brauchst.`: if it's a headline may remove the dot at the end?
      - see `Mall` slide
      - but on the `Menschen Und Projekte` slide there's a dot which can make more sence, because it's a whole sentence
      - I think make all the same
    - [ ] probably all, but at least the most of the icon texts should be translated to German?
  - [ ] `Mall` slide:
    - [ ] probably all of the icon texts should be translated to German?
  - [ ] `Menschen Und Projekte` slide:
    - [ ] `Menschen Und Projekte` header icon text  →  `Menschen und Projekte`
    - [ ] probably all of the icon texts should be translated to German?

Bildschirmfoto 2023-12-15 um 15 21 18

Bildschirmfoto 2023-12-15 um 15 41 35

- [ ] `Veränderung  Schaffen`  →  `Veränderung  schaffen`
  - [x] `E-Mail-Adresse`  →  `E-Mail Adresse`

Bildschirmfoto 2023-12-15 um 15 59 01

- [ ] Footer:
  - [ ] items should be translated
  - [ ] `Kontaktiere uns`:
    - [x] `Frag uns einfach…`  →  `Frag uns einfach …`
      - [x] perfect would be to use the ellipses letter for the three dots `…`

Bildschirmfoto 2023-12-15 um 16 13 21

#### Functionallity

- [x] if links link to the same page – like the header links do – scroll to the anker
  - because otherwise the user gets the impression that they are on a different page
  - and it's a nice animation, too
- [x] header link `kontakt` has no functionallity
  - anchor `#contact` seems not to exist
- [x] button `MEHR INFORMATIONEN` has no functionallity

Bildschirmfoto 2023-12-15 um 12 08 20

- [x] button `PERSÖNLICHER KONTAKT` has no functionallity
  - same as above

Bildschirmfoto 2023-12-15 um 12 24 17

- [ ] `Veränderung  Schaffen`:
  - [x] button `WEITER` has no functionality

Bildschirmfoto 2023-12-15 um 15 59 01

- [ ] Footer:
  - [ ] most items have no functionallity
  - [ ] `Kontaktiere uns`:
    - [ ] no e-mail is send

### LINKED ISSUE #103: 🔧 [Refactor] Optimize Resources
## 🔧 Refactor

Optimize Resources.
Currently the placeholder image for the video takes up 1/5 of the page size. Ensure we compress all videos and images as much as possible.
This applies especially on the placeholder image and all video resources.

### LINKED ISSUE #106: 🔧 [Refactor] Menu style
## 🔧 Refactor

Investigate the main menu style changes in edge cases:
- What happens if you scroll up again after you scrolled through the page
- Does the menu look good when you go back to intro video page
- When scrolling does the menu align with style?

### PR DESCRIPTION
**Pull request by maeckes-infinitylabs**
## 🍰 Pullrequest

PR to fix visual bugs, improves mobile view and optimizes the application.

### Issues

- fixes #50 
- fixes #103
- fixes #106 

### Todo

- [x] improve header handling
- [x] insert last feedback from #50

### CODE REVIEW

File: presenter/src/components/menu/FooterMenu.vue [hunk 1]
```diff
@@ -4,17 +4,21 @@
...
-          <AnchorLink href="/" :label="$t('menu.footer.instagram')"></AnchorLink>
-          <AnchorLink href="/" :label="$t('menu.footer.telegram')"></AnchorLink>
+          <div class="footer-links">
+            <AnchorLink class="min-helper" href="/" :label="$t('menu.footer.home')"></AnchorLink>
+            <AnchorLink href="/" :label="$t('menu.footer.worldCoffeeHouse')"></AnchorLink>
+            <AnchorLink
+              class="min-width-remover"
+              href="/"
+              :label="$t('menu.footer.mall')"
+            ></AnchorLink>
```
Comment (ulfgebhardt) [inline presenter/src/components/menu/FooterMenu.vue:14]: correct anchors?

**Review by ulfgebhardt — APPROVED** [review]
Besides very minor things on mobile I'd think its perfect. Please merge!
