### PR TITLE
fix(backend): search user in subscription

### LINKED ISSUE #1922: 🐛 [Bug] DM Button: Making a Meeting private has no effect on visibility
## 🐛 Bug

DM Button: Making a Meeting private has no effect on visibility.

Even if we start the Meeting again, the privat flag is not saved nor does it affect the visibility of the Meeting for the users

image

### PR DESCRIPTION
**Pull request by Elweyn**
### Motivation

The subscriptions can not access the context so it broke.

### Solution

This PR uses the given username to get the user instead of the context and handles the filtering through the db query.

### Issues
- fixes #1922 

### Todo

To test this we need to create a private ``my table`` or ``team table`` with multiple users moderators or viewers, open the table and then remove yourself of the ``team table`` look in the sidebar if the ``team table`` is still shown.
- [x] Test if the subscription works on kubernetes
- [x] Test if the openTables list has only accessible tables

### CODE REVIEW

File: backend/src/graphql/resolvers/TableResolver.ts [hunk 1]
```diff
@@ -384,40 +394,44 @@ export class TableResolver {
...
-    return openTables
-  }
+  const openTables: OpenTable[] = []
 
-  return []
+  dbMeetings.forEach((ids) => {
+    const meeting = arg.meetings.find((m) => ids.meetingID === m.meetingID)
+    if (meeting) openTables.push(new OpenTable(meeting, ids.id ? ids.id : 0))
+  })
+  return openTables
```
Comment (ulfgebhardt) [inline backend/src/graphql/resolvers/TableResolver.ts:434]:
```suggestion
return  dbMeetings.filter((meeting) => arg.meetings.find((m) => ids.meetingID === m.meetingID)}).map((meeting) => new OpenTable(meeting, ids.id ? ids.id : 0)
```

File: frontend/src/stores/tablesStore.ts [hunk 2]
```diff
@@ -105,6 +105,7 @@ export const useTablesStore = defineStore(
 
     /*
     watch(updateOpenTablesSubscriptionError, () => {
+      // eslint-disable-next-line no-console
```
Comment (ulfgebhardt) [inline frontend/src/stores/tablesStore.ts:108]: remove

Comment (Elweyn) [reply frontend/src/stores/tablesStore.ts]: Done

**Review by ulfgebhardt — APPROVED** [review]
