### PR TITLE
feat(presenter): fix apollo client testing

### LINKED ISSUE #84: 🔧 [Refactor] Cover Contact from Backend with Tests
## 🔧 Refactor
The functionality of connecting the frontend contact form to the backend needs a bit more uniti tests to reach the coverage

### PR DESCRIPTION
**Pull request by Mogge**
… mutation cannot be checked

### Issues
- fixes #84 

### Todo

- [X] None

### CODE REVIEW

File: presenter/src/components/inputs/ContactForm.vue [hunk 1]
```diff
@@ -127,30 +127,24 @@ const dataprivacy = ref(0)
...
       data: {
         firstName: firstname.value,
         lastName: lastname.value,
         email: email.value,
         content: message.value,
       },
     })
+      .then(() => {
+        form.value?.reset()
+        return undefined
```
Comment (ulfgebhardt) [inline presenter/src/components/inputs/ContactForm.vue:145]: I assume you must return a value? If you can remove the return I'd prefer that.

File: presenter/src/components/inputs/ContactForm.vue [hunk 2]
```diff
@@ -127,30 +127,24 @@ const dataprivacy = ref(0)
...
+      })
+      .catch(() => {})
```
Comment (ulfgebhardt) [inline presenter/src/components/inputs/ContactForm.vue:147]:
```suggestion
    try {
      await sendContactForm({
        data: {
          firstName: firstname.value,
          lastName: lastname.value,
          email: email.value,
          content: message.value,
        },
      })
      form.value?.reset()
    } catch(error){}
```

I think await syntax would be more consistent - not a blocker tho

File: presenter/src/components/inputs/NewsletterForm.vue [hunk 3]
```diff
@@ -95,28 +95,18 @@ const dataprivacy = ref(0)
...
-  console.log(err.message)
-})
+const { mutate: sendSubscribeToNewsletter } = useMutation(subscribeToNewsletterMutation)
 
 // submit form with data
 async function submitForm() {
   const isValid = await form.value?.validate()
   if (isValid?.valid) {
-    await sendSubscribeToNewsletter({ email: email.value })
+    sendSubscribeToNewsletter({ email: email.value })
```
Comment (ulfgebhardt) [inline presenter/src/components/inputs/NewsletterForm.vue:104]: consider await syntax and not mix it

**Review by ulfgebhardt — COMMENTED** [review]
Awesome ❤️

**Review by ulfgebhardt — APPROVED** [review]
